/* Builds the WebP derivatives this app serves, into public/img/, plus the
   manifest src/data/images.js that Img.jsx reads widths and intrinsic size
   from. Reads the originals at the repo root and never writes outside react/.

   Run it by hand — `npm run images` — when the artwork changes. It is NOT part
   of `npm run build`, because cwebp is a Homebrew binary that would not exist
   on another checkout; the output is committed instead. Re-runs are cheap: a
   derivative newer than its source is skipped.

   Needs: cwebp and ImageMagick (`brew install webp imagemagick`). */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "..");
const OUT = join(ROOT, "public/img");

// Per directory: the widest rung worth generating. The TOC thumbnails render
// at ~80 CSS px, so 320 already covers 3x — that cap is most of the saving.
const DIRS = [
  ["sample-data", 1280],
  ["assets/games", 320],
  ["assets/screens", 1280],
];

// No 1920 rung: nothing on this page renders above ~780 CSS px, and the widest
// real need is .shots at 100vw on a 390px phone at 3x.
const LADDER = [160, 320, 640, 1280];

const manifest = {};
let built = 0;

for (const [dir, cap] of DIRS) {
  mkdirSync(join(OUT, dir), { recursive: true });

  for (const file of readdirSync(join(SRC, dir)).sort()) {
    if (!/\.(png|jpe?g)$/i.test(file)) continue;

    const src = join(SRC, dir, file);
    const [w, h] = execFileSync("magick", ["identify", "-format", "%w %h", src])
      .toString()
      .split(" ")
      .map(Number);

    // Clamp to the source: these range from 330x717 to 4500x2538, and a
    // hardcoded ladder would upscale the small ones.
    const top = Math.min(w, cap);
    const widths = [...new Set([...LADDER.filter((x) => x < top), top])];

    for (const width of widths) {
      const out = join(OUT, dir, file.replace(/\.\w+$/, `-${width}.webp`));
      if (existsSync(out) && statSync(out).mtimeMs >= statSync(src).mtimeMs) continue;
      // The wordmarks have alpha and flat edges that ring at 80.
      const q = /^logo/.test(file) ? "92" : "80";
      execFileSync("cwebp", ["-quiet", "-q", q, "-resize", String(width), "0", src, "-o", out]);
      built++;
    }

    manifest[`${dir}/${file}`] = { w, h, widths };
  }
}

writeFileSync(
  join(ROOT, "src/data/images.js"),
  `// Generated by scripts/images.mjs. Do not edit.\nexport default ${JSON.stringify(
    manifest,
    null,
    2
  )};\n`
);

console.log(`${Object.keys(manifest).length} sources, ${built} derivatives built`);
